version: '3'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - inception
    build: requirements/mariadb
    env_file: .env
    ports:
      - "3306"
  ngnix:
    image: nginx
    container_name: nginx
    networks:
    - inception
    build: requirements/nginx
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    build: requirements/wordpress
    env_file: .env
    ports:
      - "9000"
    depends_on:
      - "mariadb"

networks:
  inception:
    name: inception
    driver: bridge

