version: '3.8'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    env_file: .env
    networks:
      - inception
    build: ./requirements/mariadb
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306"
    restart: always
    
  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wordpress:/var/www/wordpress
    build: ./requirements/wordpress
    env_file: .env
    ports:
      - "9000"
    depends_on:
      - "mariadb"
    restart: always
    
  ngnix:
    image: nginx
    container_name: nginx
    env_file: .env
    networks:
    - inception
    volumes:
      - wordpress:/var/www/wordpress
    build: ./requirements/nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    restart: always

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mhassani/data/wordpress'
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/mhassani/data/mariadb'

networks:
  inception:
    name: my_network